#!/bin/bash

ENC="gpg -c --cipher-algo AES256"
DEC="gpg -d --cipher-algo AES256"

if [[ "$#" < 1 || "$1" == "--help" || "$1" == "-h" ]]; then
    echo 'enc encrypts files and folders'
    echo 'usage: enc ./foo.d ./bar.txt'
    exit 0
fi

for fd in "$@"; do
    if [[ ${fd} =~ \.gpg ]]; then
        base="${fd%.*}"
        $DEC "$fd" > "$base"
        [[ ${base} =~ \.tar.gz ]] && tar -xf "$base" && rm "$base"
    elif [[ -f "$fd" ]]; then
        $ENC "$fd"
    elif [[ -d "$fd" ]]; then
        tar="${fd%/}.tar.gz"
        tar -cf "$tar" "$fd" && $ENC "$tar" && rm "$tar" 
    else
        echo "error file or directory '$fd' does not exist"
    fi
done
